// Build information - Auto-generated by scripts/inject-build-info.js
// This file is overwritten during the build process
// DO NOT EDIT MANUALLY

export const buildInfo = {
  sha: process.env.NEXT_PUBLIC_RELEASE_SHA || process.env.VERCEL_GIT_COMMIT_SHA || 'dev',
  shortSha: process.env.NEXT_PUBLIC_RELEASE_SHORT_SHA || 'dev',
  branch: process.env.NEXT_PUBLIC_RELEASE_BRANCH || process.env.VERCEL_GIT_COMMIT_REF || 'unknown',
  version: process.env.NEXT_PUBLIC_RELEASE_VERSION || '0.1.0',
  timestamp: process.env.NEXT_PUBLIC_RELEASE_TIMESTAMP || new Date().toISOString(),
  environment: process.env.NEXT_PUBLIC_ENVIRONMENT || process.env.VERCEL_ENV || 'development',
  serviceName: process.env.NEXT_PUBLIC_SERVICE_NAME || 'gatewayz-beta',
} as const;

export type BuildInfo = typeof buildInfo;
