import type { UserTier } from './api';

export type Model = {
  name: string;
  isFree: boolean;
  tokens: string;
  category: string;
  description: string;
  developer: string;
  context: number;
  inputCost: number;
  outputCost: number;
  modalities: string[];
  series: string;
  supportedParameters: string[];
  requiredTier?: UserTier;
  speedTier?: 'ultra-fast' | 'fast' | 'medium' | 'slow'; // Response speed indicator
  avgLatencyMs?: number; // Average time-to-first-token in milliseconds
  is_private?: boolean; // Indicates if model is on a private network (e.g., NEAR)
};

export const models: Model[] = [
  {
    name: 'gpt-5.1',
    isFree: false,
    tokens: '200B+ tokens',
    category: 'Multimodal',
    description: 'GPT-5.1 is the latest frontier-grade model in the GPT-5 series, offering stronger general-purpose reasoning, improved instruction adherence, and a more natural conversational style compared to GPT-5. It uses adaptive reasoning to allocate computation dynamically, responding quickly to simple queries while spending more depth on complex tasks. The model produces clearer, more grounded explanations with reduced jargon, making it easier to follow even on technical or multi-step problems.',
    developer: 'openai',
    context: 400,
    inputCost: 1.25,
    outputCost: 10,
    modalities: ['Text', 'Image', 'File'],
    series: 'GPT',
    supportedParameters: ['frequency_penalty', 'logit_bias', 'logprobs', 'max_tokens', 'presence_penalty', 'reasoning', 'response_format', 'seed', 'stop', 'tools', 'tool_choice', 'temperature', 'top_p'],
  },
  {
    name: 'GPT-4o mini',
    isFree: false,
    tokens: '21B tokens',
    category: 'Multimodal',
    description: 'A smaller, faster, and cheaper version of GPT-4o, with the same level of intelligence.',
    developer: 'openai',
    context: 128,
    inputCost: 0.15,
    outputCost: 0.60,
    modalities: ['Text', 'Image'],
    series: 'GPT',
    supportedParameters: ['tools', 'temperature', 'top_p'],
  },
  {
    name: 'Qwen: Qwen2 72B A16B 2507',
    isFree: true,
    tokens: '142M tokens',
    category: 'Multilingual',
    description: 'Qwen2-72B-A16B-Instruct-2507 is a multilingual, instruction-tuned mixture-of-experts language model based on the Qwen2-72B architecture, with 16B active parameters per forward ...',
    developer: 'qwen',
    context: 262,
    inputCost: 0,
    outputCost: 0,
    modalities: ['Text', 'File'],
    series: 'Qwen',
    supportedParameters: ['tools', 'temperature'],
  },
  {
    name: 'Qwen: Qwen2 57B A14B 2507',
    isFree: false,
    tokens: '77.4M tokens',
    category: 'Multilingual',
    description: 'Qwen2-57B-A14B-Instruct-2507 is a multilingual, instruction-tuned mixture-of-experts language model based on the Qwen2-57B architecture, with 14B active parameters per forward ...',
    developer: 'qwen',
    context: 262,
    inputCost: 0.15,
    outputCost: 0.85,
    modalities: ['Text', 'File'],
    series: 'Qwen',
    supportedParameters: ['tools', 'temperature', 'top_p'],
  },
  {
    name: 'Switchpoint Router',
    isFree: false,
    tokens: '495M tokens',
    category: 'Router',
    description: 'Switchpoint AI\'s router instantly analyzes your request and directs it to the optimal AI from an ever-evolving library. As the world of LLMs advances, our router gets smarter, ensuring you always ...',
    developer: 'switchpoint',
    context: 131,
    inputCost: 0.85,
    outputCost: 3.40,
    modalities: ['Text'],
    series: 'Other',
    supportedParameters: ['temperature'],
  },
  {
    name: 'MoonshotAI: Kimi K2',
    isFree: true,
    tokens: '20.1B tokens',
    category: 'Multilingual',
    description: 'Kimi K2 is a powerful multilingual model with a large context window, developed by Moonshot AI.',
    developer: 'moonshotai',
    context: 200,
    inputCost: 0,
    outputCost: 0,
    modalities: ['Text', 'File'],
    series: 'Kimi',
    supportedParameters: ['temperature', 'top_p'],
  },
  {
    name: 'Google: Gemini 2.0 Flash',
    isFree: false,
    tokens: '18.5B tokens',
    category: 'Multimodal',
    description: 'Fast and efficient Gemini model optimized for speed and performance with multimodal capabilities.',
    developer: 'google',
    context: 1024,
    inputCost: 0.075,
    outputCost: 0.3,
    modalities: ['Text', 'Image', 'File'],
    series: 'Gemini',
    supportedParameters: ['tools', 'temperature', 'top_p'],
  },
  {
    name: 'Google: Gemini 2.1 Pro',
    isFree: false,
    tokens: '19.5B tokens',
    category: 'Multimodal',
    description: 'The latest and most capable Gemini model from Google, with advanced multimodal reasoning.',
    developer: 'google',
    context: 1024,
    inputCost: 0.5,
    outputCost: 1.5,
    modalities: ['Text', 'Image', 'File'],
    series: 'Gemini',
    supportedParameters: ['tools', 'temperature', 'top_p'],
  },
  {
    name: 'Anthropic: Claude 3.5 Sonnet',
    isFree: false,
    tokens: '19.2B tokens',
    category: 'Multimodal',
    description: 'Claude 3.5 Sonnet sets new industry standards for intelligence, speed, and cost, outperforming competitor models and previous generation.',
    developer: 'anthropic',
    context: 200,
    inputCost: 0.25,
    outputCost: 1.25,
    modalities: ['Text', 'Image'],
    series: 'Claude',
    supportedParameters: ['tools', 'temperature', 'top_p'],
  },
  {
    name: 'Meta: Llama 3.1 405B',
    isFree: false,
    tokens: '18.8B tokens',
    category: 'Language',
    description: 'The most powerful model in the Llama 3.1 series, with a massive 405 billion parameters for unparalleled performance.',
    developer: 'meta',
    context: 128,
    inputCost: 0.9,
    outputCost: 2.5,
    modalities: ['Text'],
    series: 'Llama',
    supportedParameters: ['temperature', 'top_p'],
  },
  {
    name: 'Arch-Router-1.5B',
    isFree: true,
    tokens: '19.2B tokens',
    category: 'Router',
    description: 'Arch-Router-1.5B is a routing model based on Qwen2.5-1.5B-Instruct, designed for intelligent request routing and preference tasks.',
    developer: 'katanemo',
    context: 256,
    inputCost: 0,
    outputCost: 0,
    modalities: ['Text'],
    series: 'Other',
    supportedParameters: ['temperature', 'top_p'],
  },
  {
    name: 'deepseek-v3-1',
    isFree: false,
    tokens: '671B tokens',
    category: 'Reasoning',
    description: 'DeepSeek V3 is a powerful Mixture-of-Experts model with 671B total parameters and 37B activated per token. Features multi-head latent attention and DeepSeekMoE architecture for enhanced performance and efficiency.',
    developer: 'alpaca-network',
    context: 64,
    inputCost: 0.27,
    outputCost: 1.10,
    modalities: ['Text'],
    series: 'DeepSeek',
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    speedTier: 'fast',
    is_private: true,
  },
  // Alibaba Cloud Models
  {
    name: 'Qwen2.5 72B',
    isFree: false,
    tokens: '131K tokens',
    category: 'General Purpose',
    description: 'Alibaba Qwen2.5 72B is a high-performance multilingual language model with advanced reasoning and instruction-following capabilities. Supports over 30 languages with excellent performance across multiple domains.',
    developer: 'alibaba',
    context: 131,
    inputCost: 0.07,
    outputCost: 0.14,
    modalities: ['Text'],
    series: 'Qwen',
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    speedTier: 'fast',
  },
  {
    name: 'Qwen2.5 32B',
    isFree: false,
    tokens: '131K tokens',
    category: 'General Purpose',
    description: 'Alibaba Qwen2.5 32B is a high-efficiency multilingual model optimized for performance and cost-effectiveness. Excellent for content generation, summarization, and multilingual tasks.',
    developer: 'alibaba',
    context: 131,
    inputCost: 0.03,
    outputCost: 0.06,
    modalities: ['Text'],
    series: 'Qwen',
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    speedTier: 'ultra-fast',
  },
  {
    name: 'Qwen2.5 7B',
    isFree: true,
    tokens: '131K tokens',
    category: 'General Purpose',
    description: 'Alibaba Qwen2.5 7B is a lightweight, open-source multilingual model ideal for edge deployment and quick prototyping. Free tier model with good quality for smaller inference workloads.',
    developer: 'alibaba',
    context: 131,
    inputCost: 0,
    outputCost: 0,
    modalities: ['Text'],
    series: 'Qwen',
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    speedTier: 'ultra-fast',
  },
  {
    name: 'Qwen2 VL 72B',
    isFree: false,
    tokens: '131K tokens',
    category: 'Multimodal',
    description: 'Alibaba Qwen2 Vision-Language 72B is a multimodal model capable of understanding both text and images. Supports image analysis, visual question answering, and multimodal content generation.',
    developer: 'alibaba',
    context: 131,
    inputCost: 0.14,
    outputCost: 0.21,
    modalities: ['Text', 'Image'],
    series: 'Qwen',
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    speedTier: 'fast',
  },
  {
    name: 'Qwen Math 7B',
    isFree: false,
    tokens: '131K tokens',
    category: 'Specialized',
    description: 'Alibaba Qwen Math 7B is a specialized model optimized for mathematical reasoning and problem-solving. Ideal for educational applications and technical content generation.',
    developer: 'alibaba',
    context: 131,
    inputCost: 0.02,
    outputCost: 0.04,
    modalities: ['Text'],
    series: 'Qwen',
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    speedTier: 'ultra-fast',
  }
];
