# GitGuardian configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit

version: 2

secret:
  # Ignore specific fake API keys used in tests
  # These are NOT real secrets - they are test fixtures
  ignored-matches:
    - name: "Fake temp API key in tests"
      match: "gw_temp_abc123def"
    - name: "Fake live API key in tests"
      match: "gw_live_xyz789abc"

# Ignore test files that contain fake API keys for testing
paths-ignore:
  - "**/__tests__/**"
  - "**/src/__tests__/**"
  - "src/__tests__/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/TEMP_API_KEY_*.md"
  - "**/test-constants.ts"
  - "**/mock-fetch.ts"
