-- Create activity_log table for tracking API usage and activity
-- Safe version that won't fail if objects already exist
-- Run this in Supabase SQL Editor

-- Create table (skip if exists)
CREATE TABLE IF NOT EXISTS activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    model VARCHAR(255) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    tokens INTEGER NOT NULL DEFAULT 0,
    cost NUMERIC(10, 4) NOT NULL DEFAULT 0,
    speed NUMERIC(10, 2) DEFAULT 0,
    finish_reason VARCHAR(50) DEFAULT 'stop',
    app VARCHAR(100) DEFAULT 'API',
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes (skip if exist)
CREATE INDEX IF NOT EXISTS idx_activity_log_user_id ON activity_log(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_timestamp ON activity_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_activity_log_model ON activity_log(model);
CREATE INDEX IF NOT EXISTS idx_activity_log_provider ON activity_log(provider);
CREATE INDEX IF NOT EXISTS idx_activity_log_user_timestamp ON activity_log(user_id, timestamp DESC);

-- Enable Row Level Security (safe to run multiple times)
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist, then recreate
DROP POLICY IF EXISTS "Users can view own activity" ON activity_log;
DROP POLICY IF EXISTS "Service role can insert activity" ON activity_log;

-- Create policies
CREATE POLICY "Users can view own activity"
    ON activity_log
    FOR SELECT
    USING (auth.uid()::text = user_id::text);

CREATE POLICY "Service role can insert activity"
    ON activity_log
    FOR INSERT
    WITH CHECK (true);

-- Grant permissions (safe to run multiple times)
GRANT SELECT ON activity_log TO authenticated;
GRANT INSERT ON activity_log TO service_role;

-- Add comment
COMMENT ON TABLE activity_log IS 'Tracks all API activity for users including model calls, tokens, cost, and performance metrics';

-- Verify table was created
SELECT
    'Table created successfully!' as status,
    COUNT(*) as existing_records
FROM activity_log;
