-- Update notification templates for Resend optimization
-- This migration updates existing templates with Resend-optimized HTML

-- Update low_balance_trial template
UPDATE notification_templates 
SET 
    html_template = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Low Trial Credits Alert</title></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">Low Trial Credits Alert</h1></div><div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;"><p style="font-size: 16px; margin-bottom: 20px;">Hello <strong>{username}</strong>,</p><p style="font-size: 16px; margin-bottom: 20px;">Your trial credits are running low!</p><div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ffc107;"><ul style="margin: 0; padding-left: 20px;"><li style="margin-bottom: 8px;"><strong>Current Credits:</strong> ${current_credits}</li><li style="margin-bottom: 8px;"><strong>Alert Threshold:</strong> ${threshold}</li>{trial_days_html}</ul></div><div style="text-align: center; margin: 30px 0;"><a href="{upgrade_url}" style="background: #007bff; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">View Plans & Upgrade</a></div><p style="font-size: 14px; color: #666; margin-top: 30px;">Best regards,<br>The <strong>{app_name}</strong> Team</p></div></body></html>',
    updated_at = NOW()
WHERE id = 'low_balance_trial';

-- Update low_balance_paid template
UPDATE notification_templates 
SET 
    html_template = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Low Account Balance Alert</title></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">Low Account Balance Alert</h1></div><div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;"><p style="font-size: 16px; margin-bottom: 20px;">Hello <strong>{username}</strong>,</p><p style="font-size: 16px; margin-bottom: 20px;">Your account balance is running low!</p><div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #dc3545;"><ul style="margin: 0; padding-left: 20px;"><li style="margin-bottom: 8px;"><strong>Current Credits:</strong> ${current_credits}</li><li style="margin-bottom: 8px;"><strong>Alert Threshold:</strong> ${threshold}</li><li style="margin-bottom: 8px;"><strong>Current Plan:</strong> {plan_name}</li></ul></div><div style="text-align: center; margin: 30px 0;"><a href="{billing_url}" style="background: #28a745; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">Add Credits Now</a></div><p style="font-size: 14px; color: #666; margin-top: 30px;">Best regards,<br>The <strong>{app_name}</strong> Team</p></div></body></html>',
    updated_at = NOW()
WHERE id = 'low_balance_paid';

-- Update trial_expiring template
UPDATE notification_templates 
SET 
    html_template = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Trial Expiring Soon</title></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); color: #333; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">Trial Expiring Soon</h1></div><div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;"><p style="font-size: 16px; margin-bottom: 20px;">Hello <strong>{username}</strong>,</p><p style="font-size: 16px; margin-bottom: 20px;">Your free trial is expiring in <strong>{remaining_days} day(s)</strong>!</p><div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ffc107;"><ul style="margin: 0; padding-left: 20px;"><li style="margin-bottom: 8px;"><strong>Trial End Date:</strong> {trial_end_date}</li><li style="margin-bottom: 8px;"><strong>Remaining Credits:</strong> ${remaining_credits}</li><li style="margin-bottom: 8px;"><strong>Remaining Tokens:</strong> {remaining_tokens:,}</li><li style="margin-bottom: 8px;"><strong>Remaining Requests:</strong> {remaining_requests:,}</li></ul></div><div style="text-align: center; margin: 30px 0;"><a href="{upgrade_url}" style="background: #007bff; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">Upgrade Now</a></div><p style="font-size: 14px; color: #666; margin-top: 30px;">Best regards,<br>The <strong>{app_name}</strong> Team</p></div></body></html>',
    updated_at = NOW()
WHERE id = 'trial_expiring';

-- Update trial_expired template
UPDATE notification_templates 
SET 
    html_template = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Trial Expired</title></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%); color: #333; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">Trial Expired</h1></div><div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;"><p style="font-size: 16px; margin-bottom: 20px;">Hello <strong>{username}</strong>,</p><p style="font-size: 16px; margin-bottom: 20px;">Your free trial has expired.</p><p style="font-size: 16px; margin-bottom: 20px;">To continue using the API, please upgrade to a paid plan.</p><div style="text-align: center; margin: 30px 0;"><a href="{upgrade_url}" style="background: #007bff; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">Upgrade Now</a></div><p style="font-size: 14px; color: #666; margin-top: 30px;">Best regards,<br>The <strong>{app_name}</strong> Team</p></div></body></html>',
    updated_at = NOW()
WHERE id = 'trial_expired';

-- Update credit_added template
UPDATE notification_templates 
SET 
    html_template = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Credits Added</title></head><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%); color: #333; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">Credits Added to Your Account</h1></div><div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;"><p style="font-size: 16px; margin-bottom: 20px;">Hello <strong>{username}</strong>,</p><p style="font-size: 16px; margin-bottom: 20px;">${credits_added} credits have been added to your account.</p><div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #28a745;"><p style="margin: 0; font-size: 18px;"><strong>New Balance: ${new_balance}</strong></p></div><p style="font-size: 16px; margin-bottom: 20px;">Thank you for using <strong>{app_name}</strong>!</p><p style="font-size: 14px; color: #666; margin-top: 30px;">Best regards,<br>The <strong>{app_name}</strong> Team</p></div></body></html>',
    updated_at = NOW()
WHERE id = 'credit_added';

-- Add comment about Resend optimization
COMMENT ON TABLE notification_templates IS 'Email templates optimized for Resend email service with modern HTML design and responsive layout';
